import { Feather } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { ScrollView, StatusBar, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { SafeAreaView, useSafeAreaInsets } from "react-native-safe-area-context";
import { subscribeToMechanicRequests } from "../../services/owner/bookingService";
import type { BookingRequest } from "../../types/owner/booking";

const COLORS = { canvas:"#0B1115",card:"#151E25",text:"#F7F9FA",muted:"#A1ABB2",line:"#354249",red:"#F51F3B",bar:"#D9233C" };
type Period = "WEEK"|"MONTH"|"ALL";
const DAYS = ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
function amount(value:string) { return Number(value.replace(/[^\d.]/g,"")) || 0; }
function peso(value:number) { return new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP",maximumFractionDigits:0}).format(value); }

export default function EarningsScreen() {
  const router=useRouter(); const insets=useSafeAreaInsets(); const [period,setPeriod]=useState<Period>("WEEK"); const [bookings,setBookings]=useState<BookingRequest[]>([]);
  useEffect(()=>subscribeToMechanicRequests(setBookings),[]);
  const completed=useMemo(()=>bookings.filter((item)=>item.status==="completed"),[bookings]);
  const data=useMemo(()=>{const now=new Date(); const start=new Date(now); if(period==="WEEK") start.setDate(now.getDate()-6); if(period==="MONTH") start.setDate(now.getDate()-29); start.setHours(0,0,0,0); return period==="ALL"?completed:completed.filter(item=>new Date(item.updatedAt)>=start);},[completed,period]);
  const total=data.reduce((sum,item)=>sum+amount(item.startingPrice),0); const average=data.length?total/data.length:0;
  const weeklyBars=useMemo(()=>DAYS.map((_,day)=>{const target=new Date(); const shift=(target.getDay()+6)%7; target.setDate(target.getDate()-shift+day); return completed.filter(item=>{const date=new Date(item.updatedAt);return date.toDateString()===target.toDateString();}).reduce((sum,item)=>sum+amount(item.startingPrice),0);}),[completed]);
  const maximum=Math.max(...weeklyBars,1);
  return <SafeAreaView style={styles.safeArea} edges={["top","left","right"]}><StatusBar barStyle="light-content" backgroundColor={COLORS.canvas}/><ScrollView contentContainerStyle={[styles.content,{paddingBottom:insets.bottom+18}]} showsVerticalScrollIndicator={false}>
    <Text style={styles.title}>Earnings</Text><View style={styles.filters}>{([["WEEK","This Week"],["MONTH","This Month"],["ALL","All Time"]] as [Period,string][]).map(([key,label])=><TouchableOpacity key={key} onPress={()=>setPeriod(key)} style={[styles.filter,period===key&&styles.filterActive]}><Text style={[styles.filterText,period===key&&styles.filterTextActive]}>{label}</Text></TouchableOpacity>)}</View>
    <View style={styles.totalCard}><Text style={styles.total}>{peso(total)}</Text><Text style={styles.totalLabel}>Total Earnings</Text><View style={styles.totalIcon}><Feather name="trending-up" size={19} color="#fff"/></View></View>
    <View style={styles.summaryRow}><Metric icon="briefcase" value={String(data.length)} label="Completed Jobs"/><Metric icon="dollar-sign" value={peso(average)} label="Avg. per Job"/></View>
    <View style={styles.chartCard}><View style={styles.chartHeader}><Text style={styles.chartTitle}>Earnings Overview</Text><Text style={styles.chartNote}>This week</Text></View><View style={styles.chart}>{weeklyBars.map((value,index)=><View key={DAYS[index]} style={styles.barItem}><View style={styles.barTrack}><View style={[styles.bar,{height:`${Math.max(value?16:4,(value/maximum)*100)}%`}]} /></View><Text style={styles.day}>{DAYS[index]}</Text></View>)}</View></View>
    <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>Transactions</Text><Text style={styles.sectionNote}>{completed.length} completed</Text></View>
    {completed.length===0?<View style={styles.empty}><Feather name="credit-card" size={30} color={COLORS.muted}/><Text style={styles.emptyText}>Completed jobs will appear here.</Text></View>:completed.slice(0,8).map(item=><TouchableOpacity style={styles.transaction} key={item.id} onPress={()=>router.push({pathname:"/(onsite-mechanic)/request-details",params:{id:item.id}})}><View style={styles.vehicleIcon}><Feather name="tool" size={18} color={COLORS.text}/></View><View style={styles.transactionInfo}><Text style={styles.transactionTitle}>{item.vehicle}</Text><Text style={styles.transactionDate}>{new Date(item.updatedAt).toLocaleDateString("en-PH",{month:"short",day:"numeric",year:"numeric"})}</Text></View><Text style={styles.transactionAmount}>{item.startingPrice}</Text><Feather name="chevron-right" size={19} color={COLORS.muted}/></TouchableOpacity>)}
  </ScrollView></SafeAreaView>;
}
function Metric({icon,value,label}:{icon:keyof typeof Feather.glyphMap;value:string;label:string}){return <View style={styles.metric}><Feather name={icon} size={17} color={COLORS.muted}/><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>;}
const styles=StyleSheet.create({
  safeArea:{flex:1,backgroundColor:COLORS.canvas},content:{padding:16},title:{color:COLORS.text,fontSize:24,fontWeight:"700"},filters:{flexDirection:"row",gap:8,marginTop:18},filter:{flex:1,backgroundColor:COLORS.card,minHeight:40,justifyContent:"center",alignItems:"center",borderRadius:7},filterActive:{backgroundColor:COLORS.red},filterText:{color:COLORS.muted,fontSize:12,fontWeight:"700"},filterTextActive:{color:"#fff"},totalCard:{height:122,marginTop:14,borderRadius:11,backgroundColor:COLORS.card,justifyContent:"center",paddingHorizontal:16,position:"relative"},total:{color:COLORS.text,fontSize:30,fontWeight:"700"},totalLabel:{color:COLORS.muted,fontSize:14,marginTop:4},totalIcon:{position:"absolute",right:18,top:22,height:43,width:43,borderRadius:22,backgroundColor:COLORS.red,alignItems:"center",justifyContent:"center"},summaryRow:{flexDirection:"row",gap:10,marginTop:10},metric:{flex:1,minHeight:94,backgroundColor:COLORS.card,borderRadius:10,padding:13},metricValue:{color:COLORS.text,fontSize:20,fontWeight:"700",marginTop:8},metricLabel:{color:COLORS.muted,fontSize:13,marginTop:3},chartCard:{marginTop:18,backgroundColor:COLORS.card,borderRadius:10,padding:15},chartHeader:{flexDirection:"row",justifyContent:"space-between"},chartTitle:{color:COLORS.text,fontSize:17,fontWeight:"700"},chartNote:{color:COLORS.muted,fontSize:13},chart:{height:150,flexDirection:"row",justifyContent:"space-between",alignItems:"flex-end",marginTop:12},barItem:{width:"12%",height:"100%",alignItems:"center",justifyContent:"flex-end"},barTrack:{height:120,width:18,backgroundColor:"#202B32",borderRadius:4,justifyContent:"flex-end",overflow:"hidden"},bar:{width:"100%",backgroundColor:COLORS.bar,borderRadius:4},day:{color:COLORS.muted,fontSize:10,marginTop:6},sectionHeader:{marginTop:24,marginBottom:11,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},sectionTitle:{color:COLORS.text,fontSize:19,fontWeight:"700"},sectionNote:{color:COLORS.muted,fontSize:13},transaction:{backgroundColor:COLORS.card,borderRadius:10,padding:13,flexDirection:"row",alignItems:"center",marginBottom:9},vehicleIcon:{height:40,width:40,borderRadius:20,backgroundColor:"#303C44",justifyContent:"center",alignItems:"center"},transactionInfo:{marginLeft:11,flex:1},transactionTitle:{color:COLORS.text,fontSize:16,fontWeight:"700"},transactionDate:{color:COLORS.muted,fontSize:12,marginTop:3},transactionAmount:{color:COLORS.text,fontSize:16,fontWeight:"700"},empty:{alignItems:"center",paddingVertical:40,gap:10},emptyText:{color:COLORS.muted,fontSize:15}
});
