import { Feather } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { useRef, useState } from "react";
import { ActivityIndicator, Alert, ScrollView, StatusBar, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { SafeAreaView, useSafeAreaInsets } from "react-native-safe-area-context";
import { useShopDashboard } from "../../hooks/useShopDashboard";
import { logout } from "../../services/auth";
import { saveShopProfile } from "../../services/shopOwnerService";

const C = { bg: "#090A0C", card: "#191A1D", text: "#ECE8E6", muted: "#B7B2B0", line: "#303135", red: "#F52239", green: "#17834E" };

export default function ShopProfile() {
  const router = useRouter(); const insets = useSafeAreaInsets();
  const { account, profile, profileLoading, profileError, retry } = useShopDashboard();
  const [editing, setEditing] = useState(false); const [saving, setSaving] = useState(false); const [out, setOut] = useState(false); const [error, setError] = useState<string | null>(null);
  const [form, setForm] = useState({ businessName: "", phone: "", address: "", latitude: "", longitude: "" }); const busy = useRef(false);
  const edit = () => { if (!profile) return; setForm({ businessName: profile.businessName, phone: profile.phone, address: profile.address, latitude: String(profile.latitude), longitude: String(profile.longitude) }); setError(null); setEditing(true); };
  const save = async () => { if (busy.current) return; busy.current = true; setSaving(true); setError(null); try { await saveShopProfile({ ...form, latitude: Number(form.latitude), longitude: Number(form.longitude) }); setEditing(false); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to save profile."); } finally { busy.current = false; setSaving(false); } };
  const signOut = () => Alert.alert("Log Out", "Are you sure you want to log out?", [{ text: "Cancel", style: "cancel" }, { text: "Log Out", style: "destructive", onPress: () => void (async () => { setOut(true); try { await logout(); router.replace("/(auth)/login"); } finally { setOut(false); } })() }]);
  if (profileLoading) return <State loading text="Loading profile..." />;
  if (profileError || !profile) return <State text={profileError || "Profile unavailable."} retry={retry} />;
  return <SafeAreaView style={s.safe} edges={["top", "left", "right"]}><StatusBar barStyle="light-content" backgroundColor={C.bg} />
    <ScrollView contentContainerStyle={[s.content, { paddingBottom: insets.bottom + 20 }]} showsVerticalScrollIndicator={false}>
      <View style={s.header}><View style={s.brandRow}><Text style={s.mark}>V</Text><Text style={s.brand}>Ve<Text style={s.brandRed}>Resc</Text></Text></View><TouchableOpacity style={s.bell} accessibilityLabel="Requests" onPress={() => router.push("/(shop-owner)/requests")}><Feather name="bell" size={21} color={C.text} /></TouchableOpacity></View>
      <View style={s.identity}><View style={s.avatar}><Feather name="home" size={31} color={C.red} /></View><View style={s.identityInfo}><Text style={s.name} numberOfLines={1}>{profile.businessName || account.displayName || "Auto Shop"}</Text><Text style={s.role}>Auto Shop</Text><View style={s.verified}><Feather name={profile.verified ? "check-circle" : "clock"} size={13} color="#F7EFED" /><Text style={s.verifiedText}>{profile.verified ? "Verified" : "Verification Pending"}</Text></View><TouchableOpacity style={s.editProfile} onPress={edit} activeOpacity={0.8}><Feather name="edit-2" size={13} color="#F7EFED" /><Text style={s.editProfileText}>Edit Profile</Text></TouchableOpacity></View></View>
      {editing ? <View style={s.editCard}><Text style={s.editTitle}>Edit Shop Profile</Text><Input label="Shop name" value={form.businessName} onChange={(v) => setForm((x) => ({ ...x, businessName: v }))} /><Input label="Contact number" value={form.phone} phone onChange={(v) => setForm((x) => ({ ...x, phone: v }))} /><Input label="Shop address" value={form.address} onChange={(v) => setForm((x) => ({ ...x, address: v }))} /><Input label="Shop latitude" value={form.latitude} onChange={(v) => setForm((x) => ({ ...x, latitude: v }))} /><Input label="Shop longitude" value={form.longitude} onChange={(v) => setForm((x) => ({ ...x, longitude: v }))} />{error && <Text style={s.error}>{error}</Text>}<TouchableOpacity style={s.primary} disabled={saving} onPress={() => void save()}>{saving ? <ActivityIndicator color="#F7EFED" /> : <Text style={s.primaryText}>Save Shop Profile</Text>}</TouchableOpacity><TouchableOpacity style={s.cancel} onPress={() => setEditing(false)}><Text style={s.cancelText}>Cancel</Text></TouchableOpacity></View> : <>
        <View style={s.shortcuts}><Shortcut icon="map" title="Public Listing" onPress={() => router.push("/(shop-owner)/public-listing")} /><Shortcut icon="shield" title="Verification" onPress={() => router.push("/(shop-owner)/verification")} /><Shortcut icon="edit-2" title="Edit Profile" onPress={edit} /></View>
        <View style={s.menu}><MenuRow icon="settings" title="Account Settings" onPress={edit} /><MenuRow icon="user" title="Contact Details" onPress={edit} /><MenuRow icon="help-circle" title="Help & Support" onPress={() => router.push("/(shop-owner)/verification")} last /></View>
        <TouchableOpacity style={s.logout} disabled={out} onPress={signOut}>{out ? <ActivityIndicator color={C.red} /> : <><Feather name="log-out" size={18} color={C.red} /><Text style={s.logoutText}>Log Out</Text></>}</TouchableOpacity>
      </>}
    </ScrollView>
  </SafeAreaView>;
}

function State({ loading, text, retry }: { loading?: boolean; text: string; retry?: () => void }) { return <SafeAreaView style={s.safe}><View style={s.state}>{loading ? <ActivityIndicator size="large" color={C.red} /> : <Feather name="alert-circle" size={32} color={C.red} />}<Text style={s.stateText}>{text}</Text>{retry && <TouchableOpacity style={s.primary} onPress={retry}><Text style={s.primaryText}>Try Again</Text></TouchableOpacity>}</View></SafeAreaView>; }
function Shortcut({ icon, title, onPress }: { icon: keyof typeof Feather.glyphMap; title: string; onPress: () => void }) { return <TouchableOpacity style={s.shortcut} onPress={onPress} activeOpacity={0.75}><View style={s.shortcutIcon}><Feather name={icon} size={22} color={C.text} /></View><Text style={s.shortcutTitle} numberOfLines={1}>{title}</Text></TouchableOpacity>; }
function MenuRow({ icon, title, onPress, last }: { icon: keyof typeof Feather.glyphMap; title: string; onPress: () => void; last?: boolean }) { return <TouchableOpacity style={[s.menuRow, last && s.lastMenuRow]} onPress={onPress} activeOpacity={0.7}><Feather name={icon} size={20} color={C.muted} /><Text style={s.menuTitle}>{title}</Text><View style={s.spacer} /><Feather name="chevron-right" size={21} color={C.muted} /></TouchableOpacity>; }
function Input({ label, value, onChange, phone }: { label: string; value: string; onChange: (v: string) => void; phone?: boolean }) { return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput style={s.input} value={value} onChangeText={onChange} keyboardType={phone ? "phone-pad" : "default"} /></View>; }

const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: C.bg }, content: { paddingHorizontal: 14, paddingTop: 3, flexGrow: 1 }, header: { height: 46, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 4 }, brandRow: { flexDirection: "row", alignItems: "center" }, mark: { color: C.red, fontSize: 30, lineHeight: 35, fontWeight: "900", fontStyle: "italic", marginRight: 5 }, brand: { color: C.text, fontSize: 19, fontWeight: "800" }, brandRed: { color: C.red }, bell: { width: 42, height: 42, alignItems: "center", justifyContent: "center" },
  identity: { minHeight: 142, flexDirection: "row", alignItems: "center", paddingHorizontal: 15, paddingVertical: 14, borderRadius: 16, backgroundColor: C.red }, avatar: { width: 88, height: 88, borderRadius: 44, backgroundColor: "#F7EFED", alignItems: "center", justifyContent: "center", overflow: "hidden" }, identityInfo: { marginLeft: 14, flex: 1 }, name: { color: "#F7EFED", fontSize: 20, lineHeight: 27, fontWeight: "800" }, role: { color: "#F7EFED", fontSize: 14, lineHeight: 20 }, verified: { alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: 5, marginTop: 4 }, verifiedText: { color: "#F7EFED", fontSize: 12, fontWeight: "700" }, editProfile: { alignSelf: "flex-start", minWidth: 118, minHeight: 32, borderWidth: 1, borderColor: "rgba(255,255,255,.75)", borderRadius: 8, paddingHorizontal: 10, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, marginTop: 7 }, editProfileText: { color: "#F7EFED", fontSize: 12, fontWeight: "700" },
  shortcuts: { flexDirection: "row", justifyContent: "space-around", marginTop: 16, marginBottom: 18 }, shortcut: { flex: 1, alignItems: "center", gap: 7, minHeight: 82 }, shortcutIcon: { width: 58, height: 58, borderRadius: 29, backgroundColor: C.card, borderWidth: 1, borderColor: "#3A3B3F", alignItems: "center", justifyContent: "center" }, shortcutTitle: { color: C.text, fontSize: 12, lineHeight: 17, textAlign: "center" }, menu: { backgroundColor: C.card, borderRadius: 12, marginTop: 2, paddingHorizontal: 13, paddingVertical: 3, borderWidth: 1, borderColor: C.line }, menuRow: { minHeight: 54, flexDirection: "row", alignItems: "center", gap: 12, borderBottomWidth: 1, borderBottomColor: "#2B2C2F", paddingHorizontal: 2 }, lastMenuRow: { borderBottomWidth: 0 }, menuTitle: { color: C.text, fontSize: 15, lineHeight: 21, fontWeight: "500" }, spacer: { flex: 1 }, logout: { height: 54, borderWidth: 1, borderColor: C.red, borderRadius: 11, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 9, marginTop: 16 }, logoutText: { color: C.red, fontSize: 15, fontWeight: "700" },
  state: { flex: 1, alignItems: "center", justifyContent: "center", gap: 14, padding: 30 }, stateText: { color: C.muted, fontSize: 16, textAlign: "center" }, editCard: { backgroundColor: C.card, borderRadius: 12, padding: 17, marginTop: 17 }, editTitle: { color: C.text, fontSize: 20, fontWeight: "700" }, field: { marginTop: 15 }, label: { color: C.text, fontSize: 14, fontWeight: "600", marginBottom: 7 }, input: { color: C.text, backgroundColor: C.bg, borderWidth: 1, borderColor: C.line, borderRadius: 9, minHeight: 49, paddingHorizontal: 13, fontSize: 16 }, primary: { backgroundColor: C.red, minHeight: 52, alignItems: "center", justifyContent: "center", borderRadius: 9, marginTop: 17 }, primaryText: { color: "#F7EFED", fontSize: 15, fontWeight: "700" }, cancel: { minHeight: 45, alignItems: "center", justifyContent: "center" }, cancelText: { color: C.text, fontSize: 15, fontWeight: "700" }, error: { color: "#FF9AA8", fontSize: 14, marginTop: 12 },
});
