import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { collection, onSnapshot, query, Timestamp, where } from "firebase/firestore";
import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

import { auth, db } from "../../services/firebase";

type HistoryItem = { id: string; bookingType: "onsite-mechanic" | "towing-company" | "shop-owner"; providerName: string; vehicle: string; vehiclePlate: string; status: string; problem?: string; towingType?: string; startingPrice: string; createdAt?: Timestamp };
const C = { bg: "#F7F7F7", card: "#FFFFFF", text: "#1A1A1A", muted: "#7A7A7A", border: "#EDEDED", red: "#D32F2F", success: "#2E7D32" };

export default function HistoryScreen() {
  const router = useRouter(); const [items, setItems] = useState<HistoryItem[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { const uid = auth.currentUser?.uid; if (!uid) { setLoading(false); return; } return onSnapshot(query(collection(db, "bookings"), where("customerId", "==", uid)), (snapshot) => { setItems(snapshot.docs.map((document) => ({ id: document.id, ...document.data() } as HistoryItem)).filter((item) => ["onsite-mechanic", "towing-company", "shop-owner"].includes(item.bookingType)).sort((a, b) => (b.createdAt?.toDate().getTime() ?? 0) - (a.createdAt?.toDate().getTime() ?? 0))); setLoading(false); }, () => setLoading(false)); }, []);
  const grouped = useMemo(() => items, [items]);
  const openDetails = (item: HistoryItem) => router.push({ pathname: item.bookingType === "towing-company" ? "/(v_owner)/towing-booking/booking-detail" : item.bookingType === "shop-owner" ? "/(v_owner)/shop-booking/booking-detail" : "/(v_owner)/mechanic-booking/booking-detail", params: { bookingId: item.id } });
  const kind = (item: HistoryItem) => item.bookingType === "towing-company" ? "TOWING" : item.bookingType === "shop-owner" ? "AUTO SHOP" : "ONSITE MECHANIC";
  return <SafeAreaView style={s.safe} edges={["top", "left", "right"]}><View style={s.header}><Text style={s.title}>History</Text><Text style={s.subtitle}>All vehicle service requests</Text></View><ScrollView contentContainerStyle={s.content}>{loading ? <ActivityIndicator color={C.red} style={{ marginTop: 56 }} /> : grouped.length === 0 ? <View style={s.empty}><Ionicons name="time-outline" size={38} color={C.muted} /><Text style={s.emptyTitle}>No history yet</Text><Text style={s.muted}>Your towing, mechanic, and auto-shop requests will appear here.</Text></View> : grouped.map((item) => <Pressable key={item.id} style={s.card} onPress={() => openDetails(item)}><View style={s.top}><Text style={s.type}>{kind(item)}</Text><Text style={[s.status, item.status === "completed" && s.completed]}>{item.status.replace(/_/g, " ")}</Text></View><Text style={s.provider}>{item.providerName}</Text><View style={s.vehicleRow}><Ionicons name="car-sport-outline" size={15} color={C.muted} /><Text style={s.vehicle}>{item.vehicle} · {item.vehiclePlate}</Text></View><Text style={s.detail}>{item.problem || item.towingType || "Service request"}</Text><View style={s.bottom}><Text style={s.date}>{item.createdAt?.toDate().toLocaleDateString() || "Recent"}</Text><View style={s.priceRow}><Text style={s.price}>{item.startingPrice}</Text><Ionicons name="chevron-forward" size={16} color={C.red} /></View></View></Pressable>)}</ScrollView></SafeAreaView>;
}
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: C.bg }, header: { paddingHorizontal: 20, paddingTop: 10, paddingBottom: 14, backgroundColor: C.card, borderBottomWidth: 1, borderBottomColor: C.border }, title: { color: C.text, fontSize: 24, fontWeight: "700" }, subtitle: { color: C.muted, fontSize: 13, marginTop: 3 }, content: { padding: 16, paddingBottom: 32, gap: 12 }, card: { backgroundColor: C.card, borderRadius: 14, borderWidth: 1, borderColor: C.border, padding: 14 }, top: { flexDirection: "row", justifyContent: "space-between", gap: 8 }, type: { color: C.red, fontSize: 11, fontWeight: "800", letterSpacing: .5 }, status: { color: C.muted, fontSize: 12, textTransform: "capitalize" }, completed: { color: C.success, fontWeight: "700" }, provider: { color: C.text, fontSize: 16, fontWeight: "700", marginTop: 10 }, vehicleRow: { flexDirection: "row", alignItems: "center", gap: 5, marginTop: 7 }, vehicle: { color: C.muted, fontSize: 13 }, detail: { color: C.muted, fontSize: 13, marginTop: 5 }, bottom: { borderTopWidth: 1, borderTopColor: C.border, flexDirection: "row", justifyContent: "space-between", marginTop: 12, paddingTop: 10 }, date: { color: C.muted, fontSize: 12 }, priceRow: { flexDirection: "row", alignItems: "center", gap: 5 }, price: { color: C.text, fontSize: 14, fontWeight: "700" }, empty: { alignItems: "center", paddingTop: 90, gap: 10 }, emptyTitle: { color: C.text, fontSize: 17, fontWeight: "700" }, muted: { color: C.muted, fontSize: 13, textAlign: "center" } });
