// app/(owner)/index.styles.ts
import { StyleSheet } from "react-native";

import { colors } from "../../constants/owner/theme";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.background },

  fullscreenMap: { ...StyleSheet.absoluteFillObject },

  topOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 16,
    paddingTop: 4,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 4,
    marginBottom: 12,
  },
  greetingSmall: {
    fontSize: 12,
    color: colors.textSecondary,
    textShadowColor: "rgba(255,255,255,0.9)",
    textShadowRadius: 3,
  },
  greetingName: {
    fontSize: 20,
    fontWeight: "800",
    color: colors.textPrimary,
    textShadowColor: "rgba(255,255,255,0.9)",
    textShadowRadius: 3,
  },
  headerIcons: { flexDirection: "row", alignItems: "center", gap: 10 },
  iconButton: {
    position: "relative",
    backgroundColor: colors.white,
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  notifDot: {
    position: "absolute",
    top: 6,
    right: 7,
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: colors.primary,
    borderWidth: 1.5,
    borderColor: colors.white,
  },

  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.white,
    borderRadius: 14,
    paddingHorizontal: 14,
    height: 46,
    gap: 8,
    marginBottom: 8,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
  },
  searchPlaceholder: { color: colors.textMuted, fontSize: 14 },

  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    alignSelf: "flex-start",
    backgroundColor: "rgba(255,255,255,0.9)",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
  },
  locationText: { fontSize: 12, color: colors.textSecondary, fontWeight: "600" },

  recenterButtonWrap: {
    position: "absolute",
    right: 16,
  },
  recenterButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },

  bottomPanel: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: -4 },
    elevation: 10,
    overflow: "hidden",
  },
  dragHandleArea: {
    paddingTop: 10,
    paddingBottom: 8,
    alignItems: "center",
  },
  bottomPanelHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.border,
  },
  bottomPanelContent: { paddingHorizontal: 16, paddingBottom: 16 },

  towingButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.primary,
    borderRadius: 18,
    padding: 14,
    marginTop: 2,
    marginBottom: 18,
    gap: 12,
    shadowColor: colors.primaryDark,
    shadowOpacity: 0.3,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  towingIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
  },
  towingTextWrap: { flex: 1 },
  towingTitle: { color: colors.white, fontSize: 16, fontWeight: "800" },
  towingSubtitle: { color: "rgba(255,255,255,0.85)", fontSize: 12, marginTop: 2 },

  sectionTitle: { fontSize: 17, fontWeight: "800", color: colors.textPrimary, marginBottom: 10 },
  listingHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 4,
  },
  listingCount: { fontSize: 12, color: colors.textMuted },

  categoryRow: { gap: 10, paddingBottom: 20, paddingRight: 8 },
  categoryChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: colors.white,
  },
  categoryChipActive: { backgroundColor: colors.primary },
  categoryChipText: { fontSize: 13, fontWeight: "600", color: colors.primary },
  categoryChipTextActive: { color: colors.white },

  // ---- Nearby Providers: horizontal marketplace-style cards ----
  listingList: { flexDirection: "column" },
  listingCard: {
    flexDirection: "row",
    width: "100%",
    minHeight: 116,
    backgroundColor: colors.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 12,
    padding: 10,
    gap: 12,
  },
  listingCardSelected: {
    borderColor: colors.primary,
    borderWidth: 1.5,
  },
  listingThumb: {
    width: 84,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "stretch",
  },
  listingThumbText: { color: colors.white, fontSize: 20, fontWeight: "800" },
  listingBody: { flex: 1, justifyContent: "space-between" },
  listingTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  listingName: { flex: 1, fontSize: 14, fontWeight: "700", color: colors.textPrimary },
  listingServiceRow: { flexDirection: "row", alignItems: "center", gap: 4, marginTop: 3 },
  listingServiceText: { fontSize: 12, fontWeight: "600", color: colors.primary },
  listingMetaRow: { flexDirection: "row", alignItems: "center", gap: 4, marginTop: 5 },
  listingMetaText: { fontSize: 11, color: colors.textSecondary },
  listingMetaTextMuted: { fontSize: 11, color: colors.textMuted },
  listingMetaDot: { fontSize: 11, color: colors.textMuted, marginHorizontal: 1 },
  listingBottomRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 6,
  },
  listingPrice: { fontSize: 12, fontWeight: "700", color: colors.textPrimary },
  onsiteBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: colors.surfaceAlt,
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  onsiteBadgeText: { fontSize: 10, fontWeight: "700", color: colors.primary },
});