import { Ionicons } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { collection, onSnapshot, query, where } from "firebase/firestore";
import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

import { auth, db } from "../../services/firebase";
import { subscribeToMyVehicles } from "../../services/owner/vehicleService";
import type { SavedVehicle } from "../../types/owner/vehicle";

type VehicleHistoryItem = { id: string; bookingType: string; providerName: string; status: string; problem?: string; towingType?: string; startingPrice: string; createdAt?: { toDate?: () => Date }; vehicleId: string };
const C = { bg: "#F7F7F7", card: "#FFFFFF", text: "#1A1A1A", muted: "#7A7A7A", border: "#EDEDED", red: "#D32F2F" };

export default function VehicleHistoryScreen() {
  const router = useRouter(); const { vehicleId } = useLocalSearchParams<{ vehicleId?: string }>(); const [vehicle, setVehicle] = useState<SavedVehicle | null>(null); const [items, setItems] = useState<VehicleHistoryItem[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { try { return subscribeToMyVehicles((vehicles) => setVehicle(vehicles.find((item) => item.vehicleId === vehicleId) ?? null), () => setVehicle(null)); } catch { return; } }, [vehicleId]);
  useEffect(() => { const uid = auth.currentUser?.uid; if (!uid || !vehicleId) { setLoading(false); return; } return onSnapshot(query(collection(db, "bookings"), where("customerId", "==", uid)), (snapshot) => { setItems(snapshot.docs.map((document) => ({ id: document.id, ...document.data() } as VehicleHistoryItem)).filter((item) => item.vehicleId === vehicleId).sort((a, b) => (b.createdAt?.toDate?.().getTime() ?? 0) - (a.createdAt?.toDate?.().getTime() ?? 0))); setLoading(false); }, () => setLoading(false)); }, [vehicleId]);
  const title = useMemo(() => vehicle ? `${vehicle.make} ${vehicle.model}` : "Vehicle History", [vehicle]);
  const openDetails = (item: VehicleHistoryItem) => router.push({ pathname: item.bookingType === "towing-company" ? "/(v_owner)/towing-booking/booking-detail" : item.bookingType === "shop-owner" ? "/(v_owner)/shop-booking/booking-detail" : "/(v_owner)/mechanic-booking/booking-detail", params: { bookingId: item.id } });
  return <SafeAreaView style={s.safe} edges={["top", "left", "right"]}><View style={s.header}><Pressable onPress={() => router.back()} style={s.back}><Ionicons name="chevron-back" size={22} color={C.text} /></Pressable><View><Text style={s.title}>{title}</Text><Text style={s.subtitle}>{vehicle?.plateNumber || "Service history"}</Text></View></View><ScrollView contentContainerStyle={s.content}>{loading ? <ActivityIndicator color={C.red} style={{ marginTop: 48 }} /> : items.length === 0 ? <View style={s.empty}><Ionicons name="time-outline" size={36} color={C.muted} /><Text style={s.emptyTitle}>No history yet</Text><Text style={s.muted}>Services requested for this vehicle will appear here.</Text></View> : items.map((item) => <Pressable key={item.id} style={s.card} onPress={() => openDetails(item)}><View style={s.cardTop}><Text style={s.type}>{item.bookingType === "towing-company" ? "TOWING" : item.bookingType === "shop-owner" ? "AUTO SHOP" : "ONSITE MECHANIC"}</Text><Text style={s.status}>{item.status.replace(/_/g, " ")}</Text></View><Text style={s.provider}>{item.providerName}</Text><Text style={s.detail}>{item.problem || item.towingType || "Service request"}</Text><View style={s.bottom}><Text style={s.date}>{item.createdAt?.toDate?.().toLocaleDateString() || "Recent"}</Text><View style={s.priceRow}><Text style={s.price}>{item.startingPrice}</Text><Ionicons name="chevron-forward" size={16} color={C.red} /></View></View></Pressable>)}</ScrollView></SafeAreaView>;
}
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: C.bg }, header: { flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: C.card, borderBottomWidth: 1, borderBottomColor: C.border, padding: 16 }, back: { width: 36, height: 36, borderRadius: 18, alignItems: "center", justifyContent: "center", backgroundColor: C.bg }, title: { color: C.text, fontSize: 20, fontWeight: "700" }, subtitle: { color: C.muted, fontSize: 13, marginTop: 2 }, content: { padding: 16, paddingBottom: 32, gap: 12 }, card: { backgroundColor: C.card, borderRadius: 14, borderWidth: 1, borderColor: C.border, padding: 14 }, cardTop: { flexDirection: "row", justifyContent: "space-between", gap: 8 }, type: { color: C.red, fontSize: 11, fontWeight: "800", letterSpacing: .5 }, status: { color: C.muted, fontSize: 12, textTransform: "capitalize" }, provider: { color: C.text, fontSize: 16, fontWeight: "700", marginTop: 10 }, detail: { color: C.muted, fontSize: 13, marginTop: 4 }, bottom: { borderTopWidth: 1, borderTopColor: C.border, flexDirection: "row", justifyContent: "space-between", marginTop: 12, paddingTop: 10 }, date: { color: C.muted, fontSize: 12 }, priceRow: { flexDirection: "row", alignItems: "center", gap: 5 }, price: { color: C.text, fontSize: 14, fontWeight: "700" }, empty: { alignItems: "center", paddingTop: 90, gap: 10 }, emptyTitle: { color: C.text, fontSize: 17, fontWeight: "700" }, muted: { color: C.muted, fontSize: 13, textAlign: "center" } });
