import { Feather } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { ScrollView, StatusBar, StyleSheet, Switch, Text, TouchableOpacity, View } from "react-native";
import { SafeAreaView, useSafeAreaInsets } from "react-native-safe-area-context";
import { auth } from "../../services/firebase";
import { subscribeToTowingRequests } from "../../services/owner/towingService";
import type { TowingBookingRequest } from "../../types/owner/towing";

const C={canvas:"#0B1115",card:"#151E25",text:"#F7F9FA",muted:"#A1ABB2",status:"#2A363E",red:"#F51F3B",line:"#53616A"};
function amount(value:string){return Number(value.replace(/[^\d.]/g,""))||0}
function label(status:TowingBookingRequest["status"]){return status==="pending"?"New request":status==="en_route"?"On the way":status==="in_progress"?"In progress":status==="accepted"?"Accepted":status==="arrived"?"Arrived":status}
export default function TowingCompanyDashboard(){
  const router=useRouter(),insets=useSafeAreaInsets();const[online,setOnline]=useState(true);const[bookings,setBookings]=useState<TowingBookingRequest[]>([]);
  useEffect(()=>subscribeToTowingRequests(setBookings),[]);
  const pending=bookings.filter(b=>b.status==="pending").length;
  const active=useMemo(()=>bookings.filter(b=>["accepted","en_route","arrived","in_progress"].includes(b.status)),[bookings]);
  const earnings=useMemo(()=>{const start=new Date();start.setDate(start.getDate()-6);start.setHours(0,0,0,0);return bookings.filter(b=>b.status==="completed"&&new Date(b.updatedAt)>=start).reduce((sum,b)=>sum+amount(b.startingPrice),0)},[bookings]);
  const jobs=useMemo(()=>bookings.filter(b=>!["completed","cancelled","rejected"].includes(b.status)).slice(0,3),[bookings]);
  const open=(id:string)=>router.push({pathname:"/(towing-company)/request-details",params:{id}});
  return <SafeAreaView style={s.safe} edges={["top","left","right"]}><StatusBar barStyle="light-content" backgroundColor={C.canvas}/><ScrollView contentContainerStyle={[s.content,{paddingBottom:insets.bottom+18}]} showsVerticalScrollIndicator={false}>
    <View style={s.top}><Text style={s.title}>Dashboard</Text><TouchableOpacity style={s.bell}><Feather name="bell" size={27} color={C.text}/><View style={s.dot}/></TouchableOpacity></View>
    <Text style={s.greeting}>Good day,</Text><Text style={s.name}>{auth.currentUser?.displayName||"Towing Service"}</Text>
    <View style={s.availability}><View><View style={s.onlineRow}><Text style={s.onlineText}>{online?"Available":"Unavailable"}</Text><View style={[s.onlineDot,!online&&s.offlineDot]}/></View><Text style={s.hint}>{online?"Receiving towing requests":"Not receiving requests"}</Text></View><Switch value={online} onValueChange={setOnline} trackColor={{false:"#3A474F",true:"#65737B"}} thumbColor="#fff" style={s.switch}/></View>
    <View style={s.stats}><Stat value={String(pending)} label="New Requests"/><Stat value={String(active.length)} label="Active Tows"/><Stat value={new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP",maximumFractionDigits:0}).format(earnings)} label="This Week"/></View>
    <View style={s.section}><Text style={s.sectionTitle}>Today’s Tows</Text><TouchableOpacity onPress={()=>router.push("/(towing-company)/requests")}><Text style={s.viewAll}>View All</Text></TouchableOpacity></View>
    {jobs.length===0?<View style={s.empty}><Feather name="truck" size={28} color={C.muted}/><Text style={s.emptyText}>No active towing jobs today.</Text></View>:jobs.map(job=><View style={s.job} key={job.id}><View style={s.jobTop}><View style={s.status}><Text style={s.statusText}>{label(job.status)}</Text></View><Text style={s.time}>{new Date(job.createdAt).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</Text></View><Text style={s.vehicle}>{job.vehicle}</Text><View style={s.detailRow}><Feather name="map-pin" size={15} color={C.muted}/><Text style={s.detail}>{job.pickupLocation}</Text></View><View style={s.detailRow}><Feather name="flag" size={15} color={C.muted}/><Text style={s.detail}>{job.destination}</Text></View><Text style={s.concern}>{job.towingType}</Text><View style={s.actions}><TouchableOpacity style={s.secondary} onPress={()=>open(job.id)}><Text style={s.secondaryText}>View Details</Text></TouchableOpacity><TouchableOpacity style={s.primary} onPress={()=>open(job.id)}><Text style={s.primaryText}>{job.status==="pending"?"Review":"Update"}</Text></TouchableOpacity></View></View>)}
  </ScrollView></SafeAreaView>
}
function Stat({value,label}:{value:string;label:string}){return <View style={s.stat}><Text style={s.statValue}>{value}</Text><Text style={s.statLabel}>{label}</Text></View>}
const s=StyleSheet.create({
 safe:{flex:1,backgroundColor:C.canvas},content:{paddingHorizontal:16,paddingTop:14},top:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},title:{color:C.text,fontSize:24,fontWeight:"700"},bell:{padding:10,position:"relative"},dot:{position:"absolute",top:7,right:8,height:8,width:8,borderRadius:4,backgroundColor:C.red},greeting:{marginTop:18,color:C.muted,fontSize:16},name:{marginTop:2,color:C.text,fontSize:22,fontWeight:"700"},availability:{marginTop:16,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},onlineRow:{flexDirection:"row",alignItems:"center",gap:6},onlineText:{color:C.text,fontSize:16,fontWeight:"700"},onlineDot:{width:8,height:8,borderRadius:4,backgroundColor:C.text},offlineDot:{backgroundColor:C.muted},hint:{marginTop:5,color:C.muted,fontSize:14},switch:{transform:[{scaleX:1.1},{scaleY:1.1}]},stats:{flexDirection:"row",gap:8,marginTop:20},stat:{flex:1,minHeight:88,justifyContent:"center",alignItems:"center",borderRadius:10,backgroundColor:C.card},statValue:{color:C.text,fontSize:20,fontWeight:"700"},statLabel:{marginTop:7,color:C.muted,fontSize:12,textAlign:"center"},section:{marginTop:26,marginBottom:12,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},sectionTitle:{color:C.text,fontSize:19,fontWeight:"700"},viewAll:{color:C.red,fontSize:15,fontWeight:"700"},empty:{backgroundColor:C.card,borderRadius:10,alignItems:"center",gap:10,paddingVertical:30},emptyText:{color:C.muted,fontSize:15},job:{marginBottom:12,borderRadius:10,backgroundColor:C.card,padding:16},jobTop:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},status:{alignItems:"center",borderRadius:6,paddingHorizontal:8,paddingVertical:5,backgroundColor:C.status},statusText:{color:C.text,fontSize:11,fontWeight:"600"},time:{color:C.muted,fontSize:13},vehicle:{marginTop:10,color:C.text,fontSize:19,fontWeight:"700"},detailRow:{flexDirection:"row",alignItems:"center",gap:6,marginTop:6},detail:{color:C.muted,fontSize:15,flex:1},concern:{marginTop:6,marginLeft:21,color:C.muted,fontSize:15},actions:{flexDirection:"row",gap:10,marginTop:16},secondary:{flex:1,height:46,borderColor:C.line,borderWidth:1,borderRadius:7,alignItems:"center",justifyContent:"center"},secondaryText:{color:C.text,fontSize:15,fontWeight:"700"},primary:{flex:.92,height:46,borderRadius:7,alignItems:"center",justifyContent:"center",backgroundColor:C.red},primaryText:{color:"#fff",fontSize:15,fontWeight:"700"}
});
