import { Feather } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { ScrollView, StatusBar, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { SafeAreaView, useSafeAreaInsets } from "react-native-safe-area-context";
import { subscribeToTowingRequests } from "../../services/owner/towingService";
import type { TowingBookingRequest } from "../../types/owner/towing";
const C={canvas:"#0B1115",card:"#151E25",text:"#F7F9FA",muted:"#A1ABB2",status:"#2A363E",red:"#F51F3B"};
type Filter="ALL"|"NEW"|"ONGOING"|"COMPLETED"|"CANCELLED";
const FILTERS:[Filter,string][]=[["ALL","All"],["NEW","New"],["ONGOING","Ongoing"],["COMPLETED","Completed"],["CANCELLED","Cancelled"]];
function group(status:TowingBookingRequest["status"]):Filter {if(status==="pending")return"NEW";if(status==="completed")return"COMPLETED";if(status==="cancelled"||status==="rejected")return"CANCELLED";return"ONGOING";}
function label(status:TowingBookingRequest["status"]){return status==="pending"?"New request":status==="en_route"?"On the way":status==="in_progress"?"In progress":status==="accepted"?"Accepted":status==="arrived"?"Arrived":status==="completed"?"Completed":status==="rejected"?"Declined":"Cancelled";}
export default function TowingRequestsScreen(){const router=useRouter(),insets=useSafeAreaInsets();const[filter,setFilter]=useState<Filter>("ALL");const[bookings,setBookings]=useState<TowingBookingRequest[]>([]);useEffect(()=>subscribeToTowingRequests(setBookings),[]);const visible=useMemo(()=>filter==="ALL"?bookings:bookings.filter(b=>group(b.status)===filter),[bookings,filter]);const open=(id:string)=>router.push({pathname:"/(towing-company)/request-details",params:{id}});
return <SafeAreaView style={s.safe} edges={["top","left","right"]}><StatusBar barStyle="light-content" backgroundColor={C.canvas}/><ScrollView contentContainerStyle={[s.content,{paddingBottom:insets.bottom+18}]} showsVerticalScrollIndicator={false}><Text style={s.title}>My Bookings</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}>{FILTERS.map(([key,text])=><TouchableOpacity key={key} style={[s.filter,filter===key&&s.active]} onPress={()=>setFilter(key)}><Text style={[s.filterText,filter===key&&s.activeText]}>{text}</Text></TouchableOpacity>)}</ScrollView>{visible.length===0?<View style={s.empty}><Feather name="truck" size={28} color={C.muted}/><Text style={s.emptyText}>No {filter==="ALL"?"":"matching "}bookings.</Text></View>:visible.map(b=><TouchableOpacity key={b.id} style={s.card} onPress={()=>open(b.id)} activeOpacity={.75}><View style={s.cardTop}><View style={s.status}><Text style={s.statusText}>{label(b.status)}</Text></View><Text style={s.time}>{new Date(b.createdAt).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</Text></View><View style={s.vehicleRow}><Text style={s.vehicle}>{b.vehicle}</Text><Feather name="chevron-right" size={24} color={C.muted}/></View><View style={s.row}><View style={s.pin}><Feather name="map-pin" size={18} color={C.text}/></View><View style={s.route}><Text style={s.routeLabel}>Pickup</Text><Text style={s.location} numberOfLines={1}>{b.pickupLocation}</Text><Text style={s.routeLabel}>Destination</Text><Text style={s.location} numberOfLines={1}>{b.destination}</Text></View></View></TouchableOpacity>)}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.canvas},content:{paddingHorizontal:16,paddingTop:14},title:{color:C.text,fontSize:24,fontWeight:"700"},filters:{gap:9,paddingTop:18,paddingBottom:16},filter:{minHeight:42,justifyContent:"center",paddingHorizontal:16,borderRadius:7,backgroundColor:C.card},active:{backgroundColor:C.red},filterText:{color:C.text,fontSize:14,fontWeight:"600"},activeText:{color:"#fff"},card:{borderRadius:10,backgroundColor:C.card,padding:16,marginBottom:12},cardTop:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},status:{borderRadius:6,backgroundColor:C.status,paddingHorizontal:9,paddingVertical:5},statusText:{color:C.text,fontSize:13,fontWeight:"600"},time:{color:C.muted,fontSize:14},vehicleRow:{marginTop:12,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},vehicle:{color:C.text,fontSize:19,fontWeight:"700"},row:{marginTop:11,flexDirection:"row",alignItems:"center",gap:9},pin:{height:32,width:32,borderRadius:16,backgroundColor:"#39444C",justifyContent:"center",alignItems:"center"},route:{flex:1},routeLabel:{color:C.muted,fontSize:11,marginTop:2},location:{color:C.text,fontSize:15,marginTop:1},empty:{alignItems:"center",gap:12,paddingTop:72},emptyText:{color:C.muted,fontSize:16}});
