import { Feather } from "@expo/vector-icons";
import { useEffect, useState } from "react";
import { Alert, Pressable, ScrollView, StatusBar, StyleSheet, Switch, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { router } from "expo-router";
import { useAuth } from "../../hooks/useAuth";
import { setParkingAvailability, subscribeToMyParkingProviderListing, subscribeToParkingListing, subscribeToProviderParkingBookings, subscribeToProviderParkingSlots, type ParkingSlot } from "../../services/parkingBookingService";
import { auth } from "../../services/firebase";
import type { ParkingBooking } from "../../types/parkingBooking";

const C = { bg: "#0B1115", card: "#151E25", text: "#F7F9FA", muted: "#A1ABB2" };
export default function HomeGarageDashboard() {
  const { userProfile } = useAuth(); const [online, setOnline] = useState(false); const [configured,setConfigured]=useState(false); const [capacity,setCapacity]=useState<{totalSlots:number;availableSlots:number}|null>(null); const [reserved,setReserved]=useState(0); const [active,setActive]=useState(0); const [weekly,setWeekly]=useState(0); const [updating,setUpdating]=useState(false); const [slots,setSlots]=useState<ParkingSlot[]>([]); const [bookings,setBookings]=useState<ParkingBooking[]>([]);
  useEffect(()=>{const uid=auth.currentUser?.uid;if(!uid)return;const a=subscribeToMyParkingProviderListing((listing)=>{setConfigured(Boolean(listing));setOnline(listing?.availability==="available");});const b=subscribeToParkingListing(uid,setCapacity);const c=subscribeToProviderParkingBookings((items)=>{setBookings(items);setReserved(items.filter((item)=>item.status==="reserved").length);setActive(items.filter((item)=>item.status==="active").length);const start=new Date();start.setHours(0,0,0,0);start.setDate(start.getDate()-start.getDay());setWeekly(items.filter((item)=>new Date(item.bookedAt)>=start).length);},()=>{});const d=subscribeToProviderParkingSlots(setSlots,()=>{});return()=>{a();b();c();d();};},[]);
  const toggle=async(value:boolean)=>{if(updating)return;if(!configured){Alert.alert("Set up parking first","Add your public listing, capacity, and location before accepting bookings.",[ {text:"Open listing",onPress:()=>router.push("/(homegarage)/public-listing")},{text:"Cancel",style:"cancel"} ]);return;}setUpdating(true);try{await setParkingAvailability(value);}catch(error){Alert.alert("Availability not updated",error instanceof Error?error.message:"Please try again.");}finally{setUpdating(false);}};
  return <SafeAreaView style={s.safe} edges={["top", "left", "right"]}><StatusBar barStyle="light-content" backgroundColor={C.bg} /><ScrollView contentContainerStyle={s.content}>
    <View style={{ flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" }}><View><Text style={{color:C.muted,fontSize:15,fontFamily:"System"}}>Good day,</Text><Text style={{color:C.text,fontSize:27,fontWeight:"700",fontFamily:"System"}}>{userProfile?.displayName || "Parking Provider"}</Text></View><Pressable style={{padding:10,position:"relative"}}><Feather name="bell" size={24} color={C.text}/><View style={{position:"absolute",top:6,right:7,height:7,width:7,borderRadius:4,backgroundColor:"#F51F3B"}}/></Pressable></View>
    <View style={s.availability}><View><Text style={s.online}>{online ? "Accepting bookings" : "Not accepting bookings"}</Text><Text style={s.muted}>{online ? "Customers can reserve available slots." : "Turn this on when your spaces are ready."}</Text></View><Switch value={online} disabled={updating} onValueChange={(value)=>void toggle(value)} trackColor={{ false: "#3A474F", true: "#65737B" }} thumbColor="#FFFFFF" /></View>
    <View style={{ marginTop: 18, backgroundColor: C.card, padding: 16, borderRadius: 10 }}><Text style={{ color: C.text, fontSize: 18, fontWeight: "700" }}>{capacity ? `${capacity.availableSlots} / ${capacity.totalSlots} slots available` : "Parking setup needed"}</Text><Text style={{ color: C.muted, marginTop: 5 }}>{reserved} reserved · {active} currently parking</Text><Pressable onPress={()=>router.push("/(homegarage)/public-listing")}><Text style={{ color: "#F51F3B", fontWeight: "700", marginTop: 14 }}>{configured ? "Manage parking listing" : "Set up public listing"}</Text></Pressable></View>
    <View style={{ flexDirection: "row", gap: 8, marginTop: 12 }}><Stat value={String(weekly)} label="New this week" /><Stat value={capacity ? String(capacity.totalSlots - capacity.availableSlots) : "0"} label="Occupied slots" /><Stat value={String(active)} label="Active parking" /></View>
    <View style={{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginTop:26,marginBottom:12}}><Text style={{ color: C.text, fontSize: 21, fontWeight: "700", fontFamily:"System" }}>Parking Slots</Text><Pressable onPress={()=>router.push("/(homegarage)/public-listing")}><Text style={{color:"#F51F3B",fontSize:14,fontWeight:"700",fontFamily:"System"}}>{configured?"Manage listing ›":"Set up listing ›"}</Text></Pressable></View>
    {slots.length ? <View style={{gap:9}}>{slots.map((slot)=>{const booking=bookings.find((item)=>item.id===slot.bookingId);const busy=slot.status==="reserved";return <View key={slot.id} style={{borderRadius:10,padding:14,backgroundColor:C.card,borderWidth:1,borderColor:"#26323A",flexDirection:"row",alignItems:"center"}}><Text style={{color:C.text,fontSize:21,fontWeight:"800",width:50,fontFamily:"System"}}>#{slot.slotNumber}</Text><View style={{flex:1}}><Text style={{color:C.text,fontSize:15,fontWeight:"700",fontFamily:"System"}}>{busy?booking?.vehicle||"Reserved":"Available"}</Text><Text style={{color:C.muted,fontSize:13,marginTop:3,fontFamily:"System"}}>{busy?booking?.vehicleType||"Parking":""}</Text></View><View style={{borderWidth:1,borderColor:busy?"#7E3D47":"#70808A",borderRadius:14,paddingHorizontal:11,paddingVertical:5}}><Text style={{color:busy?"#FFB8C2":C.text,fontSize:11,fontWeight:"700",fontFamily:"System"}}>{busy?"OCCUPIED":"AVAILABLE"}</Text></View></View>;})}</View> : <View style={{ backgroundColor:C.card,borderRadius:10,padding:18 }}><Text style={{ color:C.muted,fontSize:15 }}>Set your parking capacity in Public Listing to create slots.</Text></View>}
    <Text style={{ color: C.text, fontSize: 19, fontWeight: "700", marginTop: 26, marginBottom: 10 }}>Today Activity</Text>
    <View style={{ flexDirection:"row",gap:8 }}><Stat value={String(bookings.filter((item)=>new Date(item.bookedAt).toDateString()===new Date().toDateString()).length)} label="Reservations"/><Stat value={String(active)} label="Parked now"/><Stat value={String(bookings.filter((item)=>item.status==="completed"&&item.parkingEndedAt&&new Date(item.parkingEndedAt).toDateString()===new Date().toDateString()).length)} label="Completed"/></View>
    <View style={{ flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginTop:26,marginBottom:10 }}><Text style={{ color:C.text,fontSize:19,fontWeight:"700" }}>Active Parking</Text><Pressable onPress={()=>router.push("/(homegarage)/requests")}><Text style={{color:"#F51F3B",fontWeight:"700"}}>View bookings</Text></Pressable></View>
    {bookings.filter((item)=>item.status==="reserved"||item.status==="active").slice(0,5).map((item)=><View key={item.id} style={{backgroundColor:C.card,borderRadius:10,padding:14,marginBottom:8,flexDirection:"row",alignItems:"center"}}><Feather name="navigation" size={19} color="#F51F3B"/><View style={{marginLeft:10,flex:1}}><Text style={{color:C.text,fontWeight:"700"}}>Slot #{item.slotNumber} · {item.vehicle}</Text><Text style={{color:C.muted,fontSize:13,marginTop:3}}>{item.vehicleType} · {item.status === "active" ? "Parking" : "Reserved"}</Text></View><Text style={{color:item.status==="active"?"#7DE29A":"#FFB8C2",fontSize:12,fontWeight:"700"}}>{item.status.toUpperCase()}</Text></View>)}
    {!bookings.some((item)=>item.status==="reserved"||item.status==="active") && <View style={{backgroundColor:C.card,borderRadius:10,padding:20,alignItems:"center"}}><Feather name="calendar" size={25} color={C.muted}/><Text style={{color:C.text,fontWeight:"700",marginTop:8}}>No parking activity yet</Text><Text style={{color:C.muted,textAlign:"center",marginTop:4}}>Your activity appears here when customers reserve a slot.</Text></View>}
    <View style={s.stats}><Stat value="0" label="New Bookings" /><Stat value="0" label="Occupied Slots" /><Stat value="₱0" label="This Week" /></View>
    <Text style={s.section}>Parking overview</Text><View style={s.empty}><Feather name="navigation" size={28} color={C.muted} /><Text style={s.emptyTitle}>Set up your parking lot</Text><Text style={s.muted}>Add your location, capacity, and parking rates to start receiving nearby bookings.</Text></View>
  </ScrollView></SafeAreaView>;
}
function Stat({ value, label }: { value: string; label: string }) { return <View style={s.stat}><Text style={s.statValue}>{value}</Text><Text style={s.statLabel}>{label}</Text></View>; }
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: C.bg }, content: { padding: 16, paddingBottom: 28 }, title: { color: C.text, fontFamily: "System", fontSize: 26, fontWeight: "700" }, greeting: { marginTop: 22, color: C.muted, fontFamily: "System", fontSize: 16 }, name: { color: C.text, fontFamily: "System", fontSize: 23, fontWeight: "700", marginTop: 2 }, availability: { marginTop: 18, flexDirection: "row", justifyContent: "space-between", alignItems: "center", backgroundColor: C.card, borderRadius: 10, padding: 15 }, online: { color: C.text, fontFamily: "System", fontSize: 17, fontWeight: "700" }, muted: { color: C.muted, fontFamily: "System", fontSize: 15, lineHeight: 21, marginTop: 5 }, stats: { display: "none" }, stat: { flex: 1, minHeight: 92, justifyContent: "center", alignItems: "center", backgroundColor: C.card, borderRadius: 10 }, statValue: { color: C.text, fontFamily: "System", fontSize: 22, fontWeight: "700" }, statLabel: { color: C.muted, fontFamily: "System", fontSize: 13, marginTop: 7, textAlign: "center" }, section: { display: "none" }, empty: { display: "none" }, emptyTitle: { color: C.text, fontFamily: "System", fontSize: 17, fontWeight: "700" } });
