import { Feather } from "@expo/vector-icons";
import { useEffect, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { router } from "expo-router";
import { subscribeToProviderParkingBookings } from "../../services/parkingBookingService";
import type { ParkingBooking } from "../../types/parkingBooking";

export default function ParkingSessions(){const [items,setItems]=useState<ParkingBooking[]>([]);useEffect(()=>subscribeToProviderParkingBookings(setItems,()=>{}),[]);const active=items.filter(i=>i.status==="active"),reserved=items.filter(i=>i.status==="reserved"),history=items.filter(i=>i.status==="completed").slice(0,5);return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={s.top}><View><Text style={s.title}>Parking sessions</Text><Text style={s.sub}>Track vehicles currently parked.</Text></View><View style={s.count}><Text style={s.countText}>{active.length} active</Text></View></View><Text style={s.heading}>Currently parked</Text>{active.length?active.map(i=><Card key={i.id} item={i} label="Parking" current/>):<Empty text="No vehicles are currently parked."/>}<View style={s.tabs}><View style={s.tabOn}><Text style={s.tabOnText}>Active {active.length+reserved.length}</Text></View><View style={s.tab}><Text style={s.tabText}>History</Text></View></View><Text style={s.heading}>Upcoming reservations</Text>{reserved.length?reserved.map(i=><Card key={i.id} item={i} label="Reserved"/>):<View style={s.upcoming}><Feather name="calendar" size={19} color="#A1ABB2"/><Text style={s.sub}>No upcoming reservations</Text></View>}<View style={s.historyTop}><Text style={s.heading}>Parking history</Text><Text style={s.see}>See all ›</Text></View>{history.length?history.map(i=><Card key={i.id} item={i} label="Completed"/>):<Empty text="No completed parking sessions yet."/>}</ScrollView></SafeAreaView>}
function Card({item,label,current}:{item:ParkingBooking;label:string;current?:boolean}){return <Pressable style={[s.card,current&&s.current]} onPress={()=>router.push({pathname:"/(homegarage)/parking-session-detail",params:{bookingId:item.id}})}><Feather name="navigation" size={27} color="#A1ABB2"/><View style={s.detail}><Text style={s.slot}>SLOT</Text><Text style={s.num}>{String(item.slotNumber).padStart(2,"0")}</Text><Text style={s.vehicle}>{item.vehicle}</Text><Text style={s.plate}>{item.vehiclePlate}</Text></View><View style={s.pill}><Text style={s.pillText}>{label}</Text></View></Pressable>};function Empty({text}:{text:string}){return <View style={s.empty}><Text style={s.sub}>{text}</Text></View>};
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#0B1115"},content:{padding:18,paddingBottom:32},top:{flexDirection:"row",justifyContent:"space-between",alignItems:"flex-start"},title:{color:"#F7F9FA",fontSize:27,fontWeight:"700",fontFamily:"System"},sub:{color:"#A1ABB2",fontSize:15,fontFamily:"System",marginTop:4},count:{backgroundColor:"#151E25",borderRadius:8,paddingHorizontal:12,paddingVertical:8},countText:{color:"#F7F9FA",fontSize:13,fontWeight:"700"},heading:{color:"#F7F9FA",fontSize:19,fontWeight:"700",fontFamily:"System",marginTop:26,marginBottom:11},card:{minHeight:92,backgroundColor:"#151E25",borderRadius:10,padding:15,flexDirection:"row",alignItems:"center",marginBottom:10},current:{borderLeftWidth:4,borderLeftColor:"#F51F3B"},detail:{marginLeft:14,flex:1},slot:{color:"#A1ABB2",fontSize:11,fontWeight:"700"},num:{color:"#F7F9FA",fontSize:24,fontWeight:"800",marginTop:-2},vehicle:{color:"#F7F9FA",fontSize:16,fontWeight:"700",marginTop:2},plate:{color:"#A1ABB2",fontSize:13},pill:{borderWidth:1,borderColor:"#70808A",borderRadius:14,paddingHorizontal:12,paddingVertical:6},pillText:{color:"#F7F9FA",fontSize:12,fontWeight:"700"},tabs:{flexDirection:"row",borderWidth:1,borderColor:"#2C3A43",borderRadius:9,marginTop:8},tabOn:{flex:1,backgroundColor:"#26323A",borderRadius:7,padding:11,alignItems:"center"},tab:{flex:1,padding:11,alignItems:"center"},tabOnText:{color:"#F7F9FA",fontWeight:"700",fontSize:14},tabText:{color:"#A1ABB2",fontSize:14},upcoming:{flexDirection:"row",gap:12,alignItems:"center",backgroundColor:"#151E25",borderRadius:10,padding:15},historyTop:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginTop:4},see:{color:"#A1ABB2",fontSize:14,fontWeight:"700"},empty:{backgroundColor:"#151E25",borderRadius:10,padding:20,alignItems:"center"}});
