import { Feather } from "@expo/vector-icons";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { subscribeToProviderParkingBookings } from "../../services/parkingBookingService";
import type { ParkingBooking } from "../../types/parkingBooking";

export default function ParkingSessionDetail(){const {bookingId}=useLocalSearchParams<{bookingId:string}>();const [booking,setBooking]=useState<ParkingBooking>();useEffect(()=>subscribeToProviderParkingBookings((items)=>setBooking(items.find(item=>item.id===bookingId)),()=>{}),[bookingId]);if(!booking)return <SafeAreaView style={s.safe}><Text style={s.loading}>Loading parking session...</Text></SafeAreaView>;return <SafeAreaView style={s.safe}><View style={s.header}><Pressable onPress={()=>router.back()}><Feather name="arrow-left" size={25} color="#F7F9FA"/></Pressable><Text style={s.title}>Parking session</Text><View style={{width:25}}/></View><View style={s.card}><Text style={s.label}>SLOT</Text><Text style={s.slot}>#{String(booking.slotNumber).padStart(2,"0")}</Text><Text style={s.vehicle}>{booking.vehicle}</Text><Text style={s.detail}>{booking.vehicleType} · {booking.vehiclePlate}</Text><View style={s.line}/><Row label="Status" value={booking.status}/><Row label="Reserved" value={new Date(booking.bookedAt).toLocaleString()}/>{booking.parkingStartedAt&&<Row label="Started" value={new Date(booking.parkingStartedAt).toLocaleString()}/>} {booking.parkingEndedAt&&<Row label="Ended" value={new Date(booking.parkingEndedAt).toLocaleString()}/>}</View></SafeAreaView>};function Row({label,value}:{label:string;value:string}){return <View style={s.row}><Text style={s.rowLabel}>{label}</Text><Text style={s.rowValue}>{value}</Text></View>};const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#0B1115",padding:18},header:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginTop:8},title:{color:"#F7F9FA",fontFamily:"System",fontSize:21,fontWeight:"700"},loading:{color:"#A1ABB2",marginTop:40,textAlign:"center",fontSize:16},card:{backgroundColor:"#151E25",borderRadius:12,padding:18,marginTop:28},label:{color:"#A1ABB2",fontSize:12,fontWeight:"700"},slot:{color:"#F7F9FA",fontSize:32,fontWeight:"800"},vehicle:{color:"#F7F9FA",fontSize:19,fontWeight:"700",marginTop:8},detail:{color:"#A1ABB2",fontSize:15,marginTop:4},line:{height:1,backgroundColor:"#2C3A43",marginVertical:18},row:{flexDirection:"row",justifyContent:"space-between",gap:14,marginBottom:13},rowLabel:{color:"#A1ABB2",fontSize:15},rowValue:{color:"#F7F9FA",fontSize:14,fontWeight:"600",textTransform:"capitalize",textAlign:"right",flex:1}});
