import { Feather } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { useEffect, useState } from "react";
import { Alert, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useAuth } from "../../hooks/useAuth";
import { logout } from "../../services/auth";
import { getHomeGarageVerificationProfile } from "../../services/homeGarageVerificationService";

const C = { bg: "#0B1115", card: "#151E25", text: "#F7F9FA", muted: "#A1ABB2", line: "#2A363E", red: "#F51F3B", green: "#1C8D5B" };
type Status = "PENDING" | "VERIFIED" | "REJECTED" | "INCOMPLETE";

export default function HomeGarageProfile() {
  const router = useRouter(); const { userProfile } = useAuth(); const [status, setStatus] = useState<Status>("INCOMPLETE");
  useEffect(() => { if (!userProfile?.uid) return; getHomeGarageVerificationProfile(userProfile.uid).then((profile) => setStatus(profile?.verificationStatus ?? "INCOMPLETE")).catch(() => setStatus("INCOMPLETE")); }, [userProfile?.uid]);
  const label = status === "VERIFIED" ? "Verified" : status === "PENDING" ? "Verification Pending" : status === "REJECTED" ? "Verification Rejected" : "Complete Verification";
  const signOut = () => Alert.alert("Log Out", "Are you sure you want to log out?", [{ text: "Cancel" }, { text: "Log Out", style: "destructive", onPress: () => void logout().finally(() => router.replace("/(auth)/login")) }]);
  return <SafeAreaView style={s.safe} edges={["top", "left", "right"]}><Text style={s.title}>Profile</Text><View style={s.identity}><View style={s.avatar}><Feather name="home" size={30} color={C.muted} /></View><Text style={s.name}>{userProfile?.displayName || "HomeGarage"}</Text><Text style={s.role}>Parking Lot Provider</Text><TouchableOpacity style={[s.badge, status === "VERIFIED" && s.verified]} onPress={() => router.push("/(homegarage)/verification")}><Feather name={status === "VERIFIED" ? "check-circle" : "clock"} size={12} color="#fff" /><Text style={s.badgeText}>{label}</Text></TouchableOpacity></View><View style={s.card}><Row icon="mail" title="Email" value={userProfile?.email || "Not provided"} /><Row icon="shield" title="Profile verification" value={label} onPress={() => router.push("/(homegarage)/verification")} /><Row icon="map" title="Public listing" value={status === "VERIFIED" ? "Add parking details, map pin, and photos" : "Available after verification"} onPress={() => router.push("/(homegarage)/public-listing")} /></View><TouchableOpacity style={s.logout} onPress={signOut}><Feather name="log-out" size={18} color={C.red} /><Text style={s.logoutText}>Log Out</Text></TouchableOpacity></SafeAreaView>;
}
function Row({ icon, title, value, onPress }: { icon: keyof typeof Feather.glyphMap; title: string; value: string; onPress?: () => void }) { return <TouchableOpacity style={s.row} onPress={onPress}><Feather name={icon} size={18} color={C.muted} /><View style={{ flex: 1 }}><Text style={s.rowTitle}>{title}</Text><Text style={s.rowValue}>{value}</Text></View>{onPress && <Feather name="chevron-right" size={18} color={C.muted} />}</TouchableOpacity>; }
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: C.bg, padding: 16 }, title: { color: C.text, fontSize: 24, fontWeight: "700", marginTop: 10 }, identity: { alignItems: "center", marginTop: 28, marginBottom: 28 }, avatar: { width: 68, height: 68, borderRadius: 34, alignItems: "center", justifyContent: "center", backgroundColor: C.card }, name: { color: C.text, fontSize: 19, fontWeight: "700", marginTop: 12 }, role: { color: C.muted, fontSize: 14, marginTop: 3 }, badge: { marginTop: 9, flexDirection: "row", alignItems: "center", gap: 4, borderRadius: 7, backgroundColor: "#374147", paddingHorizontal: 8, paddingVertical: 5 }, verified: { backgroundColor: C.green }, badgeText: { color: "#fff", fontSize: 11, fontWeight: "700" }, card: { backgroundColor: C.card, borderRadius: 10 }, row: { flexDirection: "row", alignItems: "center", gap: 12, padding: 16, borderBottomWidth: 1, borderBottomColor: C.line }, rowTitle: { color: C.text, fontSize: 15, fontWeight: "600" }, rowValue: { color: C.muted, fontSize: 13, marginTop: 3 }, logout: { marginTop: 24, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, borderWidth: 1, borderColor: C.red, borderRadius: 8, padding: 14 }, logoutText: { color: C.red, fontSize: 16, fontWeight: "700" } });
