import * as DocumentPicker from "expo-document-picker";
import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useRouter } from "expo-router";

import { auth } from "../../services/firebase";
import { getHomeGarageVerificationProfile, saveHomeGarageVerificationProfile } from "../../services/homeGarageVerificationService";
import { uploadVerificationFile } from "../../services/providerProfileService";

const C = { bg: "#0B1115", card: "#151E25", text: "#F7F9FA", muted: "#A1ABB2", red: "#F51F3B", border: "#354249" };
export default function HomeGarageVerification() {
  const router = useRouter(); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [status, setStatus] = useState<string | null>(null); const [validId, setValidId] = useState<{ uri: string; name: string; mimeType?: string | null; size?: number | null } | null>(null); const [form, setForm] = useState({ name: "", contactPerson: "", phone: "" });
  useEffect(() => { const uid = auth.currentUser?.uid; if (!uid) return; getHomeGarageVerificationProfile(uid).then((profile) => { if (profile) { setStatus(profile.verificationStatus); setForm({ name: profile.business.name, contactPerson: profile.business.contactPerson, phone: profile.business.phone }); } }).finally(() => setLoading(false)); }, []);
  const chooseValidId = async () => { const result = await DocumentPicker.getDocumentAsync({ type: ["image/jpeg", "image/png"], copyToCacheDirectory: true }); if (!result.canceled) { const file = result.assets[0]; setValidId({ uri: file.uri, name: file.name, mimeType: file.mimeType, size: file.size }); } };
  const submit = async () => { const uid = auth.currentUser?.uid; if (!uid || !form.name.trim() || !form.contactPerson.trim() || !form.phone.trim() || !validId) return Alert.alert("Missing information", "Complete all details and upload a valid ID."); setSaving(true); try { const validIdUrl = await uploadVerificationFile(uid, "valid-id", validId); await saveHomeGarageVerificationProfile(uid, { uid, role: "homegarage", business: { name: form.name.trim(), contactPerson: form.contactPerson.trim(), phone: form.phone.trim(), address: "", latitude: 0, longitude: 0 }, documents: { validIdUrl }, verificationStatus: "PENDING" }); setStatus("PENDING"); } catch (error) { Alert.alert("Submission failed", error instanceof Error ? error.message : "Please try again."); } finally { setSaving(false); } };
  if (loading) return <SafeAreaView style={s.safe}><ActivityIndicator color={C.red} /></SafeAreaView>;
  if (status === "PENDING" || status === "VERIFIED") return <SafeAreaView style={s.safe}><View style={s.center}><Text style={s.title}>{status === "VERIFIED" ? "HomeGarage verified" : "Verification submitted"}</Text><Text style={s.muted}>{status === "VERIFIED" ? "Your parking provider profile is verified." : "Your documents are being reviewed."}</Text><TouchableOpacity style={s.primary} onPress={() => router.back()}><Text style={s.primaryText}>Back to Profile</Text></TouchableOpacity></View></SafeAreaView>;
  const input = (key: keyof typeof form, label: string, placeholder: string) => <><Text style={s.label}>{label}</Text><TextInput value={form[key]} onChangeText={(value) => setForm((current) => ({ ...current, [key]: value }))} placeholder={placeholder} placeholderTextColor={C.muted} style={s.input} /></>;
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Text style={s.title}>Profile Verification</Text><Text style={s.muted}>Verify your parking-lot provider account before going live.</Text>{input("name", "PARKING LOT NAME", "Business name")}{input("contactPerson", "CONTACT PERSON", "Full name")}{input("phone", "PHONE", "Contact number")}<Text style={s.label}>VALID ID</Text><TouchableOpacity style={s.secondary} onPress={() => void chooseValidId()}><Text style={s.secondaryText}>{validId ? validId.name : "Upload valid ID (JPG or PNG)"}</Text></TouchableOpacity><TouchableOpacity style={s.primary} disabled={saving} onPress={() => void submit()}>{saving ? <ActivityIndicator color="#fff" /> : <Text style={s.primaryText}>Submit for Verification</Text>}</TouchableOpacity></ScrollView></SafeAreaView>;
}
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: C.bg }, content: { padding: 20, paddingBottom: 40 }, center: { flex: 1, alignItems: "center", justifyContent: "center", padding: 24, gap: 14 }, title: { color: C.text, fontSize: 24, fontWeight: "700" }, muted: { color: C.muted, fontSize: 14, lineHeight: 20, marginTop: 6 }, label: { color: C.muted, fontSize: 12, fontWeight: "700", letterSpacing: .5, marginTop: 20, marginBottom: 7 }, input: { borderWidth: 1, borderColor: C.border, backgroundColor: C.card, borderRadius: 10, padding: 14, color: C.text, fontSize: 16 }, primary: { marginTop: 26, backgroundColor: C.red, borderRadius: 10, minHeight: 52, alignItems: "center", justifyContent: "center" }, primaryText: { color: "#fff", fontSize: 16, fontWeight: "700" }, secondary: { borderWidth: 1, borderColor: C.border, backgroundColor: C.card, borderRadius: 10, padding: 14 }, secondaryText: { color: C.text, fontSize: 15, fontWeight: "600" } });
