import { Ionicons } from "@expo/vector-icons";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";
import { Alert, Pressable, ScrollView, StatusBar, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { getPublicProviderListing } from "../../../services/publicProviderListingService";
import { getActiveParkingBookingForCustomer, reserveParking, subscribeToParkingListing } from "../../../services/parkingBookingService";
import { subscribeToMyVehicles } from "../../../services/owner/vehicleService";
import type { SavedVehicle } from "../../../types/owner/vehicle";

export default function BookParking() {
  const { providerId } = useLocalSearchParams<{ providerId: string }>();
  const [name, setName] = useState(""); const [slots, setSlots] = useState<{ totalSlots: number; availableSlots: number } | null>(null);
  const [vehicles, setVehicles] = useState<SavedVehicle[]>([]); const [selected, setSelected] = useState<string | null>(null); const [notes, setNotes] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!providerId) return; let mounted=true; void getActiveParkingBookingForCustomer(providerId).then((existing)=>{if(mounted&&existing)router.replace({pathname:"/(v_owner)/parking-booking/parking-detail",params:{bookingId:existing.id}});}).catch(()=>{}); getPublicProviderListing(providerId).then((item) => { if (!item || item.role !== "homegarage") throw new Error(); setName(item.businessName); }).catch(() => Alert.alert("Parking unavailable", "This parking space is no longer available.")); const stop=subscribeToParkingListing(providerId, setSlots); return ()=>{mounted=false;stop();}; }, [providerId]);
  useEffect(() => subscribeToMyVehicles((items) => { setVehicles(items); setSelected((old) => old && items.some((v) => v.vehicleId === old) ? old : null); }, () => {}), []);
  const vehicle = vehicles.find((item) => item.vehicleId === selected);
  const book = async () => { if (!providerId || !vehicle || !name || saving) return; setSaving(true); try { const result = await reserveParking(providerId, name, vehicle, notes); router.replace({ pathname: "/(v_owner)/parking-booking/parking-detail", params: { bookingId: result.bookingId } }); } catch (e) { Alert.alert("Reservation unavailable", e instanceof Error ? e.message : "Please try again."); } finally { setSaving(false); } };
  return <SafeAreaView style={s.safe}><StatusBar barStyle="dark-content" backgroundColor="#FFFFFF" /><View style={s.header}><Pressable onPress={() => router.back()}><Ionicons name="chevron-back" size={25} color="#1A1A1A" /></Pressable><Text style={s.title}>Reserve Parking</Text><View /></View><ScrollView contentContainerStyle={s.content}><Text style={s.name}>{name || "Loading parking space..."}</Text><View style={s.capacity}><Ionicons name="car-outline" size={26} color="#D32F2F" /><View><Text style={s.capacityValue}>{slots ? `${slots.availableSlots} / ${slots.totalSlots} slots available` : "Loading availability..."}</Text><Text style={s.muted}>Your slot is reserved immediately after booking.</Text></View></View><Text style={s.label}>SELECT VEHICLE</Text>{!selected && vehicles.length > 0 && <Text style={s.vehiclePrompt}>Please select a vehicle</Text>}{vehicles.map((item) => <Pressable key={item.vehicleId} onPress={() => setSelected(item.vehicleId)} style={[s.vehicle, selected === item.vehicleId && s.selected]}><Ionicons name="car-sport-outline" size={21} color="#D32F2F" /><View style={{ flex: 1 }}><Text style={s.vehicleName}>{item.year} {item.make} {item.model}</Text><Text style={s.muted}>{item.type} · {item.plateNumber}</Text></View>{selected === item.vehicleId && <Ionicons name="checkmark-circle" size={21} color="#D32F2F" />}</Pressable>)}{!vehicles.length && <Text style={s.warning}>Add a saved vehicle first from My Vehicles.</Text>}<Text style={s.label}>NOTES (OPTIONAL)</Text><TextInput value={notes} onChangeText={setNotes} maxLength={500} multiline placeholder="Arrival notes or instructions" style={s.input} /><Pressable disabled={!vehicle || !slots?.availableSlots || saving} onPress={() => void book()} style={[s.button, (!vehicle || !slots?.availableSlots || saving) && s.disabled]}><Text style={s.buttonText}>{saving ? "Reserving..." : "Reserve Parking"}</Text></Pressable></ScrollView></SafeAreaView>;
}
const s = StyleSheet.create({ safe:{flex:1,backgroundColor:"#fff"},header:{padding:16,flexDirection:"row",justifyContent:"space-between",alignItems:"center",borderBottomWidth:1,borderColor:"#EEE"},title:{fontSize:18,fontWeight:"700",color:"#1A1A1A"},content:{padding:18,gap:12},name:{fontSize:22,fontWeight:"700",color:"#1A1A1A"},capacity:{flexDirection:"row",gap:12,alignItems:"center",backgroundColor:"#FFF3F4",padding:16,borderRadius:14},capacityValue:{fontSize:17,fontWeight:"700",color:"#1A1A1A"},muted:{fontSize:14,color:"#6B6B6B",marginTop:2},label:{fontSize:12,fontWeight:"700",color:"#6B6B6B",marginTop:12},vehiclePrompt:{fontSize:15,fontWeight:"600",color:"#6B6B6B",paddingVertical:4},vehicle:{flexDirection:"row",gap:10,alignItems:"center",borderWidth:1,borderColor:"#EEE0E0",padding:13,borderRadius:12},selected:{borderColor:"#D32F2F",backgroundColor:"#FFF8F8"},vehicleName:{fontWeight:"600",color:"#1A1A1A"},input:{minHeight:78,borderWidth:1,borderColor:"#EEE0E0",borderRadius:12,padding:12,textAlignVertical:"top"},button:{backgroundColor:"#D32F2F",padding:15,borderRadius:13,alignItems:"center",marginTop:10},disabled:{backgroundColor:"#C8CDD1"},buttonText:{color:"#fff",fontWeight:"700",fontSize:16},warning:{color:"#B3261E",fontSize:13} });

